name: surgical-vision
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - numpy>=2.1.0
    - matplotlib==3.10.3
    - opencv-python==4.11.0.86
    - torch==2.7.1
    - torchvision==0.22.1
    - timm==1.0.19
    - ultralytics==8.3.174
    - torchmetrics==1.8.0
    - tensorboard==2.20.0
    - mlflow==3.1.4
    - wandb==0.21.0
    - av==15.0.0
    - einops==0.8.1
    - omegaconf==2.3.0
    - hydra-core==1.3.2
    - lightning==2.5.2
    - seaborn==0.13.2